### ISSUE TITLE
Text color for VAN integration sync message makes text illegible

### ISSUE THREAD

**Issue by kohlee** [politics-rewired/Spoke#1512]
**Describe the bug**
When an admin selects Sync from the Integration tab, a success message appears at the bottom of the screen. Both the text color and box color are very dark and the message can only be read upon highlighting.

**To Reproduce**

1.  Go to Integrations
2. Click on Sync
3. See black-on-blue text box at the bottom of the screen

**Expected behavior**
Text color should be light enough to be legible

**Screenshots**
![Screen Shot 2022-11-01 at 12 17 12 PM](https://user-images.githubusercontent.com/66085180/199319853-e3e825b7-6dd0-4341-848e-21bc8b0b42b5.png)

**Desktop (please complete the following information):**

- OS:  iOS
- Browser: Chrome

**Comment by hiemanshu** [comment]
@politics-rewired/organizing closing this, because either intentionally (or non intentionally <--- this one) it's been fixed in 6.0.0 RC0 already. It's been upgraded to the new M(oo)UI Snackbar that fixes the issue. 

<img width="733" alt="Screenshot 2022-11-07 at 4 27 13 PM" src="https://user-images.githubusercontent.com/367605/200293802-87ba33c1-e13c-4cd1-8d23-a18b1b5d0eff.png">
